#!/usr/bin/env bash

REPO=$1
BRANCH="${2:-master}"

# Don't sync if there's a .no_sync file
[ -e .no_sync  ] || {
    # Sync notebook repo
    WORKDIR=$(mktemp -d git-XXXXXX)
    # git clone with backoff to give network whitelist time to start
    NEXT_WAIT_TIME=0
    until $(git clone --depth 1 --branch "$BRANCH" "$REPO" "$WORKDIR") ||  [ $NEXT_WAIT_TIME -eq 4 ]; do
      sleep $(( NEXT_WAIT_TIME++ ))
    done
    rm -rf "${WORKDIR}"/{.github,.gitignore,LICENSE,README.md,README.rst,CITATION.cff,USAGE.rst,docker-compose.yml,DEAfrica_notebooks_template.ipynb,DEA_notebooks_template.ipynb,Scientific_workflows,Tests} || true
    rsync --verbose --recursive "${WORKDIR}/" ~/
    rm -rf "${WORKDIR}"
    # Install Tools folder if available
    if [ -e $HOME/Tools/setup.py ]; then
        python -m pip install -e "$HOME/Tools" || true
    fi
    rm -rf "$HOME/.git"
}
