#!/usr/bin/env bash

REPO=$1
BRANCH="${2:-master}"

REPO_NAME=$(basename -- "$REPO")
REPO_DIR="${REPO_NAME%.*}"

# Don't sync if there's a .no_sync file
[ -e .no_sync  ] || {
    # Sync notebook repo
    WORKDIR=$(mktemp -d git-XXXXXX)
    # git clone with backoff to give network whitelist time to start
    NEXT_WAIT_TIME=0
    until $(git clone --depth 1 --branch "$BRANCH" "$REPO" "$WORKDIR") ||  [ $NEXT_WAIT_TIME -eq 4 ]; do
      sleep $(( NEXT_WAIT_TIME++ ))
    done
    rm -rf "${WORKDIR}"/{.git,.github,.gitignore,LICENSE,README.md,DEAfrica_notebooks_template.ipynb} || true
    rsync --verbose --recursive "${WORKDIR}/" ~/
    rm -rf "${WORKDIR}"
    # Install Tools folder if available
    python -m pip install -e "${REPO_DIR}/Tools" || true
}
