version: "3.6"

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=postgres
    expose:
      - 5432
    restart: always

  sandbox:
     build:
      context: ../docker
     environment:
       - DB_HOSTNAME=postgres
       - DB_USERNAME=postgres
       - DB_PASSWORD=opendatacubepassword
       - DB_DATABASE=postgres
       - AWS_DEFAULT_REGION=ap-southeast-2
       - AWS_ACCESS_KEY_ID=fake_id
       - AWS_SECRET_ACCESS_KEY=fake_key
       - AWS_NO_SIGN_REQUEST=YES
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
     user: ${CURRENT_UID}
     volumes:
       - ${GITHUB_WORKSPACE}/dea-notebooks:/home/jovyan/dea-notebooks
       - ${GITHUB_WORKSPACE}/tide_models:/var/share/tide_models
