name: sandbox

on:
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'

  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'

env:
  ORG: opendatacube
  IMAGE: sandbox
  BUILDER_TAG: _build_cache
  DOCKER_USER: gadockersvc


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull Cache
      run: |
        docker pull ${ORG}/${IMAGE}:latest         || true
        docker pull ${ORG}/${IMAGE}:${BUILDER_TAG} || true

    - name: Build Sandbox Docker (stage1)
      run: |
        # build and cache first stage (env_builder)
        docker build \
          --target env_builder \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --tag        ${ORG}/${IMAGE}:${BUILDER_TAG} \
          ./docker/

    - name: Build Sandbox Docker (stage2)
      run: |
        # now build second stage making sure first stage is from cache
        docker build \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --cache-from ${ORG}/${IMAGE}:latest \
          --tag        ${ORG}/${IMAGE}:latest \
          ./docker/

    - name: Build Sandbox Docker (sudo)
      run: |
        # build SUDO version
        docker build \
          --build-arg WITH_SUDO=yes \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --cache-from ${ORG}/${IMAGE}:latest \
          --tag        ${ORG}/${IMAGE}:sudo \
          ./docker/

    - name: DockerHub Push
      if: |
        github.event_name == 'push' && (
        github.ref == 'refs/heads/master'
        )

      run: |
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin
        docker push ${ORG}/${IMAGE}:${BUILDER_TAG}
        docker push ${ORG}/${IMAGE}:latest
        docker push ${ORG}/${IMAGE}:sudo
