name: Sandbox build and push

on:
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'

  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'

env:
  IMAGE_NAME: geoscienceaustralia/sandbox
  DOCKER_USER: gadockersvc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build on every push, to test the build
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        push_image_and_stages: false
        context: ./docker/

  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout git
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and Push latest Docker image
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        image_tag: latest,${{ steps.get_version.outputs.VERSION }}
        # push_git_tag: true
        context: ./docker/

    - name: Build and Push latest Docker image with Sudo
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        build_extra_args: "--build-arg=WITH_SUDO=yes"
        image_tag: sudo-latest,sudo-${{ steps.get_version.outputs.VERSION }}
        context: ./docker/
