name: Sandbox build and push latest

on:
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'

  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'

env:
  IMAGE_NAME: geoscienceaustralia/sandbox
  DOCKER_USER: gadockersvc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build on every push to test the build
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        push_image_and_stages: false
        context: ./docker

  push:
    # Pushing only happens on the Master branch
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout git
      uses: actions/checkout@v2

    - name: Get the Git tag
      id: get_version
      run: |
        git fetch --prune --unshallow
        echo ::set-output name=VERSION::$(git describe --tags)

    - name: Build and Push latest Docker image
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        image_tag: latest,${{ steps.get_version.outputs.VERSION }}
        context: ./docker

    - name: Build and Push latest sudo Docker image
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        build_extra_args: "--build-arg=WITH_SUDO=yes"
        image_tag: sudo-latest,sudo-${{ steps.get_version.outputs.VERSION }}
        context: ./docker
