name: sandbox

on:
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-sandbox.yml'
      - '.github/workflows/*sh'

env:
  ORG: opendatacube
  IMAGE: sandbox
  DOCKER_USER: gadockersvc


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: DockerHub Login
      if: github.event_name == 'push'
      run: |
        source .github/workflows/ci-helpers.sh
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin

    - name: Pull Cache (stage1)
      run: |
        source .github/workflows/ci-helpers.sh
        pull_docker_cache ${ORG}/${IMAGE}:${BUILDER_TAG} ${ORG}/${IMAGE}:${BUILDER_TAG0}

    - name: Build Sandbox Docker (stage1)
      run: |
        source .github/workflows/ci-helpers.sh
        # build and cache first stage (env_builder)
        docker build \
          --target env_builder \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --tag        ${ORG}/${IMAGE}:${BUILDER_TAG} \
          ./docker/

    - name: DockerHub Push (stage1)
      if: github.event_name == 'push'
      run: |
        source .github/workflows/ci-helpers.sh
        docker push ${ORG}/${IMAGE}:${BUILDER_TAG}

    - name: Pull Cache (stage2)
      run: |
        source .github/workflows/ci-helpers.sh
        # Remove old layers first to help with disk usage
        docker system prune --force
        pull_docker_cache ${ORG}/${IMAGE}:${MAIN_TAG} ${ORG}/${IMAGE}:latest

    - name: Build Sandbox Docker (stage2)
      run: |
        source .github/workflows/ci-helpers.sh
        # now build second stage making sure first stage is from cache
        docker build \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --cache-from ${ORG}/${IMAGE}:${MAIN_TAG} \
          --tag        ${ORG}/${IMAGE}:${MAIN_TAG} \
          ./docker/

    - name: DockerHub Push (stage2)
      if: github.event_name == 'push'
      run: |
        source .github/workflows/ci-helpers.sh
        docker push ${ORG}/${IMAGE}:${MAIN_TAG}

    - name: Build Sandbox Docker (sudo)
      run: |
        source .github/workflows/ci-helpers.sh
        # build SUDO version
        docker build \
          --build-arg WITH_SUDO=yes \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --cache-from ${ORG}/${IMAGE}:${MAIN_TAG} \
          --tag        ${ORG}/${IMAGE}:${SUDO_TAG} \
          ./docker/

    - name: DockerHub Push (sudo)
      if: github.event_name == 'push'
      run: |
        source .github/workflows/ci-helpers.sh
        docker push ${ORG}/${IMAGE}:${SUDO_TAG}
