name: Sandbox build and push a release

on:
  release:
    types:
      - created


env:
  IMAGE_NAME: geoscienceaustralia/sandbox
  DOCKER_USER: gadockersvc

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout git
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${$GITHUB_REF | cut -d / -f 3}

    - name: Build and Push latest Docker image
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        image_tag: latest,${{ steps.get_version.outputs.VERSION }}
        context: ./docker

    - name: Build and Push latest Docker image with Sudo
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ env.DOCKER_USER }}
        password: "${{ secrets.DockerPassword }}"
        build_extra_args: "--build-arg=WITH_SUDO=yes"
        image_tag: sudo-latest,sudo-${{ steps.get_version.outputs.VERSION }}
        context: ./docker
