name: Vulnerability Scan

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  actions: read
  security-events: write

jobs:
  vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        continue-on-error: true
        with:
          image-ref: 'geoscienceaustralia/sandbox:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'